services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017

  posts:
    container_name: posts
    image: posts
    build:
      context: ./posts-microservice
      dockerfile: Dockerfile
    volumes:
      - ./posts-microservice:/usr/src/app
    ports:
      - 3005:3005
    environment:
      - MONGO_URL=mongodb://mongo:27017/blog
      - POSTS_MICROSERVICE=posts

  filter:
    container_name: filter
    image: filter
    build:
      context: ./filter-microservice
      dockerfile: Dockerfile
    volumes:
      - ./filter-microservice:/usr/src/app
    ports:
      - 3006:3006
    environment:
      - POSTS_MICROSERVICE=posts
      - FILTER_MICROSERVICE=filter

  admin:
    container_name: admin
    image: admin
    build:
      context: ./admin
      dockerfile: Dockerfile
    volumes:
      - ./admin:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - posts
    environment:
      - MONGO_URL=mongodb://mongo:27017/blog
      - POSTS_MICROSERVICE=posts

  admin-frontend:
    container_name: admin-frontend
    image: admin-frontend
    build:
      context: ./admin-frontend
      dockerfile: Dockerfile
    volumes:
      - ./admin-frontend:/app
    ports:
      - 8080:8080
    depends_on:
      - admin
      - register-microfrontend
    environment:
      - MICROFRONTED_URL=http://register-microfrontend:3015

  register-microfrontend:
    container_name: register-microfrontend
    image: register-microfrontend
    build:
      context: ./register-microfrontend
      dockerfile: Dockerfile
    volumes:
      - ./register-microfrontend:/app
    ports:
      - 3015:3015
    depends_on:
      - mongo
      - admin
    environment:
      - MICROFRONTED_URL=http://register-microfrontend:3015

  blog:
    container_name: blog
    image: blog
    build:
      context: ./blog
      dockerfile: Dockerfile
    volumes:
      - ./blog:/usr/src/app
    ports:
      - 3003:3003
    depends_on:
      - posts
      - filter
    environment:
      - MONGO_URL=mongodb://mongo:27017/blog
      - POSTS_MICROSERVICE=posts
      - FILTER_MICROSERVICE=filter

  blog-frontend:
    container_name: blog-frontend
    image: blog-frontend
    build:
      context: ./blog-frontend
      dockerfile: Dockerfile
    volumes:
      - ./blog-frontend:/app
    ports:
      - 8081:8081
    depends_on:
      - blog
