services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

  posts:
    container_name: posts
    image: posts
    build:
      context: ./posts-microservice
      dockerfile: Dockerfile
    volumes:
      - ./posts-microservice:/usr/src/app
    ports:
      - 3005:3005
    environment:
      - MONGO_URL=mongodb://mongo:27017/blog
      - POSTS_MICROSERVICE=posts

  server:
    container_name: admin
    image: admin
    build:
      context: ./admin
      dockerfile: Dockerfile
    volumes:
      - ./admin:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - posts
    environment:
      - MONGO_URL=mongodb://mongo:27017/blog
      - POSTS_MICROSERVICE=posts

  client:
    container_name: admin-frontend
    image: admin-frontend
    build:
      context: ./admin-frontend
      dockerfile: Dockerfile
    volumes:
      - ./admin-frontend:/app
    ports:
      - 8080:8080
    depends_on:
      - server
